version: '3'

services:
  # node
  node:
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    container_name: node-app
    tty: true
    volumes:
      - .:/usr/src/app
    working_dir: "/usr/src/app" # working_dirはいらない？
    ports:
      - '8080:8080'